### ISSUE TITLE
How does it compare to other optimizers, such as Google Vizier and HEBO, when using a fixed cost for all experiments and no early stopping?

### ISSUE THREAD

**Issue by ad8e** [imbue-ai/carbs#2]

**Comment by abefetterman** [comment]
We have not compared to Google Vizier (I'm unsure if they have a novel algorithm for search in their public implementation or just implement others in their framework). We found it to perform slightly worse than HEBO, but slightly better than TuRBO on BBO challenge type problems where there is a fixed cost.
